SELECT COUNT(CLASSES.TYPE)
FROM CLASSES
WHERE CLASSES.TYPE = 'bb'

SELECT CLASSES.CLASS, AVG(CLASSES.NUMGUNS) AS AvgNumGuns
FROM CLASSES
WHERE CLASSES.TYPE = 'bb'
GROUP BY CLASSES.CLASS

SELECT AVG(CLASSES.NUMGUNS) AS AvgNumGuns
FROM CLASSES
WHERE CLASSES.TYPE = 'bb'

SELECT SHIPS.CLASS, MIN(SHIPS.LAUNCHED) AS FirstYear, MAX(SHIPS.LAUNCHED) AS SecondYear
FROM SHIPS
GROUP BY SHIPS.CLASS

SELECT SHIPS.CLASS, COUNT(OUTCOMES.RESULT) AS No_Sunk
FROM OUTCOMES
JOIN SHIPS ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT = 'sunk' AND 
SHIPS.CLASS IN (SELECT SHIPS.CLASS FROM SHIPS GROUP BY SHIPS.CLASS HAVING COUNT(SHIPS.NAME) > 1)
GROUP BY SHIPS.CLASS

SELECT CLASSES.COUNTRY, CONVERT(DECIMAL(20, 2), AVG(CLASSES.BORE)) AS AvgBore
FROM CLASSES
JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY COUNTRY