SELECT MOVIEEXEC.NAME, MOVIE.TITLE
FROM MOVIEEXEC
JOIN MOVIE ON MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
WHERE MOVIEEXEC.CERT# =
(SELECT MOVIE.PRODUCERC# FROM MOVIE WHERE MOVIE.TITLE = 'Star Wars')

SELECT DISTINCT MOVIEEXEC.NAME 
FROM MOVIEEXEC
JOIN MOVIE ON MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
WHERE MOVIE.TITLE IN
(SELECT STARSIN.MOVIETITLE FROM STARSIN WHERE STARSIN.STARNAME = 'Harrison Ford')

SELECT DISTINCT MOVIE.STUDIONAME, STARSIN.STARNAME
FROM MOVIE
JOIN STARSIN ON STARSIN.MOVIETITLE = MOVIE.TITLE
ORDER BY MOVIE.STUDIONAME

SELECT DISTINCT STARSIN.STARNAME, MOVIEEXEC.NETWORTH, MOVIE.TITLE
FROM STARSIN
JOIN MOVIE ON MOVIE.TITLE = STARSIN.MOVIETITLE
JOIN MOVIEEXEC ON  MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
WHERE MOVIE.PRODUCERC# IN
(SELECT MOVIEEXEC.CERT# FROM MOVIEEXEC WHERE NETWORTH >= ALL (SELECT NETWORTH FROM MOVIEEXEC))

SELECT MOVIESTAR.NAME, STARSIN.MOVIETITLE
FROM MOVIESTAR
LEFT JOIN STARSIN ON MOVIESTAR.NAME = STARSIN.STARNAME
WHERE MOVIETITLE IS NULL
