SELECT *
FROM SHIPS
LEFT JOIN CLASSES ON ships.class = CLASSES.CLASS

SELECT *
FROM ships
RIGHT JOIN classes ON ships.class = CLASSES.CLASS
WHERE SHIPS.class IS NOT NULL OR classes.class IN (SELECT ships.NAME FROM ships)

SELECT DISTINCT CLASSES.COUNTRY, SHIPS.NAME
FROM CLASSES
JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS
LEFT JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE RESULT IS NULL

SELECT SHIPS.NAME AS 'Ship Name' 
FROM SHIPS
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE NUMGUNS >= 7
AND LAUNCHED = 1916

SELECT SHIPS.NAME, BATTLES.DATE, BATTLES.NAME
FROM SHIPS
JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
WHERE OUTCOMES.RESULT = 'sunk'

SELECT SHIPS.NAME, SHIPS.LAUNCHED, CLASSES.DISPLACEMENT
FROM SHIPS
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE SHIPS.NAME = CLASSES.CLASS

SELECT *
FROM CLASSES
LEFT JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS
WHERE SHIPS.LAUNCHED IS NULL

SELECT ships.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS, OUTCOMES.RESULT
FROM ships
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.BATTLE = 'North Atlantic'