SELECT MOVIESTAR.NAME 
FROM MOVIESTAR 
WHERE MOVIESTAR.GENDER = 'F'
AND MOVIESTAR.NAME IN (SELECT MOVIEEXEC.NAME FROM MOVIEEXEC WHERE NETWORTH > 10000000)

SELECT MOVIESTAR.NAME
FROM MOVIESTAR
WHERE MOVIESTAR.NAME NOT IN
(SELECT MOVIEEXEC.NAME FROM MOVIEEXEC)

SELECT MOVIE.TITLE
FROM MOVIE
WHERE MOVIE.LENGTH > ALL (SELECT MOVIE.LENGTH FROM MOVIE WHERE MOVIE.TITLE LIKE 'Star Wars')

SELECT MOVIEEXEC.NAME, MOVIE.TITLE 
FROM MOVIEEXEC, MOVIE
WHERE MOVIEEXEC.CERT# = MOVIE.PRODUCERC# AND
MOVIEEXEC.NETWORTH > ALL (SELECT MOVIEEXEC.NETWORTH FROM MOVIEEXEC WHERE MOVIEEXEC.NAME LIKE 'Merv Griffin')

