SELECT DISTINCT CLASSES.COUNTRY
FROM CLASSES
WHERE CLASSES.NUMGUNS >= ALL (SELECT CLASSES.NUMGUNS FROM CLASSES)

SELECT DISTINCT SHIPS.CLASS
FROM SHIPS
WHERE SHIPS.NAME IN
(SELECT OUTCOMES.SHIP FROM OUTCOMES WHERE OUTCOMES.RESULT = 'sunk')

SELECT ships.CLASS, ships.NAME 
FROM ships
WHERE ships.CLASS IN
(SELECT CLASSES.CLASS FROM CLASSES WHERE BORE = 16)

SELECT OUTCOMES.BATTLE
FROM OUTCOMES
WHERE outcomes.SHIP IN
(SELECT SHIPS.NAME FROM SHIPS WHERE SHIPS.CLASS = 'Kongo')

SELECT SHIPS.NAME, SHIPS.CLASS
FROM SHIPS
WHERE SHIPS.CLASS IN 
(SELECT c.CLASS FROM CLASSES AS c 
WHERE c.NUMGUNS >= ALL (SELECT NUMGUNS FROM CLASSES
WHERE CLASSES.BORE = c.BORE))