CREATE VIEW bigger_war_than_Guadalcanal_more_ships
AS
SELECT BATTLE FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT(SHIP) > (SELECT COUNT(SHIP) FROM OUTCOMES WHERE BATTLE = 'Guadalcanal' GROUP BY BATTLE)

SELECT BATTLE FROM bigger_war_than_Guadalcanal_more_ships

CREATE VIEW bigger_war_than_Guadalcanal_more_countries
AS
SELECT BATTLE FROM OUTCOMES
LEFT JOIN SHIPS ON  SHIPS.NAME = OUTCOMES.SHIP
LEFT JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY BATTLE
HAVING COUNT(DISTINCT COUNTRY) > (
SELECT COUNT(DISTINCT COUNTRY) FROM CLASSES 
LEFT JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS
LEFT JOIN OUTCOMES ON OUTCOMES.SHIP = SHIPS.NAME
WHERE BATTLE = 'Guadalcanal' 
GROUP BY BATTLE)

SELECT BATTLE FROM bigger_war_than_Guadalcanal_more_countries

DELETE FROM OUTCOMES 
WHERE BATTLE IN (SELECT BATTLE FROM OUTCOMES GROUP BY BATTLE HAVING COUNT(SHIP) = 1)

INSERT INTO outcomes VALUES ('Missouri','Surigao Strait', 'sunk'),
('Missouri','North Cape', 'sunk'),
('Missouri','North Atlantic', 'ok');

DELETE FROM OUTCOMES
WHERE SHIP IN (
SELECT SHIP FROM OUTCOMES
WHERE RESULT = 'sunk'
GROUP BY SHIP
HAVING COUNT(result) = 2
) AND result = 'sunk'

CREATE VIEW battle_countries
AS
SELECT * FROM OUTCOMES
RIGHT JOIN SHIPS ON SHIPS.NAME = OUTCOMES.SHIP
RIGHT JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS

SELECT DISTINCT BATTLE FROM battle_countries
WHERE COUNTRY = (
SELECT COUNTRY FROM battle_countries
WHERE BATTLE = 'Guadalcanal'
)

SELECT COUNTRY, COUNT(DISTINCT BATTLE) AS country FROM OUTCOMES
right JOIN SHIPS ON SHIPS.NAME = OUTCOMES.SHIP
right JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY COUNTRY

