--1
SELECT MOVIE.TITLE, MOVIE.YEAR, MOVIE.LENGTH
FROM MOVIE
WHERE ((MOVIE.LENGTH > 120 AND MOVIE.YEAR < 2000) OR MOVIE.LENGTH IS NULL)

--2
SELECT MOVIESTAR.NAME, MOVIESTAR.GENDER
FROM MOVIESTAR
WHERE MOVIESTAR.BIRTHDATE > 1948
AND MOVIESTAR.NAME LIKE 'J%'
ORDER BY MOVIESTAR.NAME DESC

--3
SELECT STUDIONAME, COUNT(DISTINCT STARSIN.STARNAME) AS NumActors
FROM MOVIE
JOIN STARSIN ON STARSIN.MOVIETITLE = MOVIE.TITLE
GROUP BY STUDIONAME

--4
SELECT MOVIESTAR.NAME, COUNT(MOVIETITLE) AS NumMovies
FROM MOVIESTAR
LEFT JOIN STARSIN ON STARSIN.STARNAME = MOVIESTAR.NAME
GROUP BY MOVIESTAR.NAME

--5

select movietitle, starname, birthdate
from StarsIn s
JOIN (select name, birthdate
from MovieStar
where gender='M') t ON s.STARNAME = t.NAME


SELECT MOVIESTAR.NAME
FROM MOVIESTAR
WHERE MOVIESTAR.BIRTHDATE = (SELECT TOP 1 MOVIESTAR.BIRTHDATE FROM MOVIESTAR WHERE MOVIESTAR.GENDER = 'M' ORDER BY MOVIESTAR.BIRTHDATE DESC)



SELECT MOVIE.TITLE, MOVIE.YEAR, COUNT(DISTINCT STARSIN.STARNAME) AS Count_Actors
FROM MOVIE
JOIN STARSIN ON STARSIN.MOVIETITLE = MOVIE.TITLE
GROUP BY TITLE, MOVIE.YEAR
HAVING COUNT(DISTINCT STARSIN.STARNAME) > 2




