SELECT DISTINCT OUTCOMES.SHIP 
FROM OUTCOMES
WHERE OUTCOMES.SHIP LIKE 'C%' OR OUTCOMES.SHIP LIKE 'K%'

SELECT DISTINCT SHIPS.NAME, CLASSES.COUNTRY
FROM SHIPS
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
LEFT JOIN OUTCOMES ON OUTCOMES.SHIP = SHIPS.NAME
WHERE RESULT IS NULL OR RESULT = 'ok' OR RESULT = 'damaged'

SELECT DISTINCT C1.COUNTRY, (SELECT COUNT(DISTINCT OUTCOMES.SHIP) FROM OUTCOMES JOIN SHIPS ON SHIPS.NAME = OUTCOMES.SHIP right JOIN CLASSES AS C2 ON C2.CLASS = SHIPS.CLASS WHERE C1.COUNTRY = C2.COUNTRY AND (RESULT = 'sunk' OR ships.NAME is null))
FROM CLASSES C1
LEFT JOIN SHIPS ON SHIPS.CLASS = C1.CLASS
LEFT JOIN OUTCOMES ON OUTCOMES.SHIP = SHIPS.NAME
WHERE RESULT IS NULL OR SHIPS.NAME IS NULL

SELECT OUTCOMES.BATTLE 
FROM OUTCOMES
GROUP BY OUTCOMES.BATTLE
HAVING COUNT(DISTINCT OUTCOMES.SHIP) > (SELECT COUNT(DISTINCT OUTCOMES.SHIP) FROM OUTCOMES WHERE OUTCOMES.BATTLE = 'Guadalcanal' GROUP BY OUTCOMES.BATTLE)

SELECT OUTCOMES.BATTLE
FROM OUTCOMES
JOIN SHIPS ON SHIPS.NAME = OUTCOMES.SHIP
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY OUTCOMES.BATTLE
HAVING COUNT(DISTINCT CLASSES.COUNTRY) > (SELECT COUNT(DISTINCT CLASSES.COUNTRY) FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP WHERE OUTCOMES.BATTLE = 'Surigao Strait' )

SELECT DISTINCT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM SHIPS
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE CLASSES.NUMGUNS >= ALL (SELECT CLASSES.NUMGUNS FROM CLASSES WHERE CLASSES.DISPLACEMENT <= ALL (SELECT DISPLACEMENT FROM CLASSES))
AND CLASSES.DISPLACEMENT <= ALL (SELECT DISPLACEMENT FROM CLASSES)

SELECT COUNT(O1.SHIP) AS NumShips
FROM OUTCOMES AS O1
JOIN OUTCOMES AS O2 ON O1.SHIP = O2.SHIP
JOIN BATTLES AS B1 ON O1.BATTLE = B1.NAME
JOIN BATTLES AS B2 ON O2.BATTLE = B2.NAME
WHERE O1.RESULT = 'damaged' AND O2.RESULT = 'ok'
AND B1.DATE < B2.DATE

SELECT O1.SHIP
FROM OUTCOMES AS O1
JOIN OUTCOMES AS O2 ON O1.SHIP = O2.SHIP
JOIN BATTLES AS B1 ON O1.BATTLE = B1.NAME
JOIN BATTLES AS B2 ON O2.BATTLE = B2.NAME
WHERE O1.RESULT = 'damaged' AND O2.RESULT = 'ok'
AND B1.DATE < B2.DATE
AND (SELECT COUNT(DISTINCT O3.SHIP) FROM OUTCOMES AS O3 WHERE O3.BATTLE = O1.BATTLE) <
(SELECT COUNT(DISTINCT O4.SHIP) FROM OUTCOMES AS O4 WHERE O4.BATTLE = O2.BATTLE)

SELECT *
FROM SHIPS
JOIN OUTCOMES ON OUTCOMES.SHIP = SHIPS.NAME
