SELECT name FROM ships
JOIN classes ON classes.CLASS LIKE ships.CLASS
WHERE CLASSES.DISPLACEMENT	> 50000

SELECT DISTINCT NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS FROM SHIPS
JOIN CLASSES ON CLASSES.CLASS LIKE SHIPS.CLASS
JOIN OUTCOMES ON name LIKE OUTCOMES.SHIP
WHERE BATTLE = 'Guadalcanal'

SELECT DISTINCT c1.COUNTRY FROM CLASSES c1
JOIN classes c2 ON c1.COUNTRY LIKE c2.COUNTRY
WHERE c1.TYPE LIKE 'bb' AND c2.TYPE = 'bc'

SELECT O1.SHIP
FROM OUTCOMES O1, OUTCOMES O2, BATTLES B1, BATTLES B2
WHERE O1.SHIP = O2.SHIP AND
B1.NAME = O1.BATTLE AND
B2.NAME = O2.BATTLE AND
O1.RESULT LIKE 'damaged' AND
B1.DATE < B2.DATE